# Generated by Django 3.2.4 on 2021-06-23 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scraper.images')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
