# Generated by Django 3.2.4 on 2021-07-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_scrapedinfo_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='scrapedinfo',
            options={'verbose_name': 'Scraped Info'},
        ),
        migrations.RemoveField(
            model_name='scrapedinfo',
            name='images',
        ),
        migrations.RemoveField(
            model_name='scrapedinfo',
            name='text',
        ),
        migrations.AlterField(
            model_name='scrapedinfo',
            name='title',
            field=models.CharField(max_length=160),
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='scraper.parentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='scraper.parentinfo')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scraper.parentinfo'),
            preserve_default=False,
        ),
    ]
